project_id = "amufvgzrxeipylqmcfvx"

[functions.create-pix-payment]
verify_jwt = true

[functions.create-tournament-registration-pix]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.send-tournament-email]
verify_jwt = true

[functions.send-mass-email]
verify_jwt = true

[functions.create-prize-deposit]
verify_jwt = true

[functions.distribute-prizes]
verify_jwt = true

[functions.join-mini-tournament]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true
